"""
test_multipage_regression.py — Task Group 5.4 (BLOCKING multi-page regressions).

These two tests are the ONLY guard for two regressions this change actually
risks but the Group 6 ship-gate benchmarks (DP-Bench / OmniDocBench) STRUCTURALLY
CANNOT see: every benchmark doc is single-page (``page_index`` always 0), so a
cross-page ordering bug and the per-page assembly seam never surface there — both
gates pass green while the bug slips through. Hence: BLOCKING, mocked VLM.

(Under Route B — adopted 2026-05-31, see planning/spike-route-decision.md — each
page's Docling markdown is produced by ``render_markdown`` over THAT page's
element list and the pages are joined with plain ``\\n\\n``. There is no
whole-doc ``export_to_markdown(page_break_placeholder=...)`` + split anymore, so
the seam is now a per-page-assembly seam, not a placeholder-split seam. The
regressions these tests guard — cross-page bleed, dropped pages, mis-ordering —
are mechanism-independent, so the SAME boundary-integrity intent is asserted
against Route B's per-page assembly.)

(a) Promoted-middle-page ordering — asserts POSITION, not presence.
    A >=3-page doc where the MIDDLE page (index 1) is forced down the VLM route
    while pages 0 and 2 stay Docling. The promoted page-2 content must land
    BETWEEN page 1 and page 3 in the concatenated markdown — not appended at the
    end (the old append-to-end bug). Asserting "page-2 content is present
    somewhere" is INSUFFICIENT (it passes under the bug); we assert strict
    index order. Route-independent (KEPT as-is).

(b) Per-page assembly seam on a 2+ digital-page PDF — asserts page-boundary
    INTEGRITY under Route B. Each page's section contains its OWN sentinel and
    NONE of the adjacent page's, and nothing is dropped at the ``\\n\\n`` join
    (all pages present, joined with the expected single blank line). Under Route
    B the hazard is the per-page element grouping mis-bucketing items (a page's
    element leaking into a neighbour's ``render_markdown`` input, or a page's
    elements vanishing) — this catches both, the same intent as the old
    placeholder-split seam test, on the Route-B mechanism.

Fixture: ``three_page_digital.pdf`` — a genuinely 3-page DIGITAL PDF with a
unique sentinel per page (``PAGE1_SENTINEL`` / ``PAGE2_SENTINEL`` /
``PAGE3_SENTINEL``) and a unique body word per page (Alpha / Bravo / Charlie),
generated by ``tests/fixtures/make_three_page_digital.py``. Docling
markdown-escapes the underscore (``PAGE1\\_SENTINEL``), so the tests match on the
escape-free, mutually-non-substring prefixes ``PAGE1`` / ``PAGE2`` / ``PAGE3``
plus the per-page unique words.

Run with the rest of the feature suite (task 5.5):
    uv run pytest tests/test_multipage_regression.py
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest

FIXTURES = Path(__file__).parent / "fixtures"
THREE_PAGE = FIXTURES / "three_page_digital.pdf"
DIGITAL = FIXTURES / "digital_simple.pdf"

# Escape-free, mutually-non-substring per-page markers. "PAGE1"/"PAGE2"/"PAGE3"
# survive Docling's markdown escaping of the underscore in the sentinels.
_PAGE1 = "PAGE1"
_PAGE2 = "PAGE2"
_PAGE3 = "PAGE3"
# Per-page unique body words (also escape-free, and NOT substrings of the VLM
# sentinel below — so they cleanly signal whether a Docling slice survived).
_PAGE1_WORD = "Alpha"
_PAGE2_WORD = "Bravo"
_PAGE3_WORD = "Charlie"

# Distinctive content the mocked VLM returns for the promoted middle page.
# Deliberately contains NO "PAGE1/2/3" substring so it cannot alias the Docling
# page markers (a sentinel like "PAGE2_VLM..." would alias the _PAGE2 marker).
_PAGE2_VLM_SENTINEL = "MIDDLE_VLM_DELTA_SENTINEL"


def _require_three_page_fixture() -> None:
    if not THREE_PAGE.exists():
        pytest.skip(
            "three_page_digital.pdf missing — regenerate with "
            "`uv run python tests/fixtures/make_three_page_digital.py`"
        )


# ===========================================================================
# (a) Promoted-MIDDLE-page ordering — assert POSITION, not presence.
# ===========================================================================


def test_promoted_middle_page_lands_between_neighbors(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A gate-promoted MIDDLE page's VLM content sits BETWEEN its neighbors.

    Sets up the exact mixed state that exposed the append-to-end bug: a 3-page
    doc where ONLY page index 1 is promoted to the VLM (pages 0 and 2 stay
    Docling). The promoted page's distinctive VLM content must appear in the
    final markdown strictly between page 1's and page 3's content. Route-
    independent: per-page assembly (Route B) must preserve page order exactly
    as the old path did.
    """
    _require_three_page_fixture()

    from parser_service import markdown_pipeline
    from parser_service.quality_gate import Decision

    # Deterministic gate: promote ONLY the middle page (page_no == 1), keep the
    # rest. We monkeypatch the gate's RETURN VALUE (not the production
    # thresholds). evaluate_page's first positional arg is the 0-based page_no.
    def _gate(page_no: int, *args: Any, **kwargs: Any) -> Decision:
        if page_no == 1:
            return Decision("promote_to_vlm", "forced_middle_page", layer=1)
        return Decision("keep", None, None)

    monkeypatch.setattr(markdown_pipeline, "evaluate_page", _gate)

    # Mock the VLM to return distinctive page-2 content (only the middle page
    # reaches the VLM, so a single fixed response is unambiguous).
    def _mock_vlm(image_bytes: bytes, mode: str) -> dict[str, Any]:
        return {"elements": [{"type": "paragraph", "text": _PAGE2_VLM_SENTINEL}]}

    monkeypatch.setattr(markdown_pipeline, "call_vlm", _mock_vlm)

    result = markdown_pipeline.parse_to_markdown(THREE_PAGE)
    md = result["markdown"]

    # Routing sanity: page 0 and 2 kept Docling, page 1 went to the VLM, in order.
    routes = {r["page_index"]: r["route"] for r in result["page_routes"]}
    assert routes.get(0) == "docling-kept", result["page_routes"]
    assert routes.get(1) == "vlm", result["page_routes"]
    assert routes.get(2) == "docling-kept", result["page_routes"]
    assert [r["page_index"] for r in result["page_routes"]] == [0, 1, 2]

    # All three pages' content present (nothing dropped).
    assert _PAGE1 in md, md
    assert _PAGE2_VLM_SENTINEL in md, md
    assert _PAGE3 in md, md
    # The original Docling page-2 slice was OVERWRITTEN by the VLM content: the
    # middle page's unique Docling word ("Bravo") is gone.
    assert _PAGE2_WORD not in md, md

    # THE BLOCKING ASSERTION: strict POSITION order. The promoted middle page's
    # VLM content must sit BETWEEN page 1 and page 3 — not appended at the end.
    i1 = md.index(_PAGE1)
    i2 = md.index(_PAGE2_VLM_SENTINEL)
    i3 = md.index(_PAGE3)
    assert i1 < i2 < i3, (
        "promoted middle page must land between its neighbors, not be reordered "
        f"or appended; got indices page1={i1}, page2_vlm={i2}, page3={i3}\n{md}"
    )


# ===========================================================================
# (b) Per-page assembly seam (Route B) — assert page-boundary INTEGRITY,
#     not mere co-existence.
# ===========================================================================


def test_per_page_assembly_seam_no_content_crosses_page_boundary(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Route-B per-page assembly keeps each page's content on its own page.

    All pages ``keep`` (real Route-B path: per-page ``render_markdown`` over each
    page's element list, joined with ``\\n\\n``; VLM mocked but never reached).
    Asserts boundary INTEGRITY: each page's section carries its OWN markers and
    NONE of the adjacent page's, AND nothing is dropped at the seam (every page
    present, neighbouring pages joined with the expected ``\\n\\n``). The Route-B
    hazard is the per-page element grouping leaking an item into a neighbour's
    render or dropping a page's elements — this catches both.
    """
    _require_three_page_fixture()

    from parser_service import markdown_pipeline
    from parser_service.quality_gate import Decision

    # Keep every page → exercise the real per-page render_markdown assembly path.
    monkeypatch.setattr(
        markdown_pipeline,
        "evaluate_page",
        lambda *a, **k: Decision("keep", None, None),
    )
    # If the VLM is ever called here it is a bug; make it loudly wrong.
    monkeypatch.setattr(
        markdown_pipeline,
        "call_vlm",
        lambda *a, **k: {"error": "VLM must not run when every page is kept"},
    )

    result = markdown_pipeline.parse_to_markdown(THREE_PAGE)
    md = result["markdown"]

    assert all(r["route"] == "docling-kept" for r in result["page_routes"]), result["page_routes"]
    assert [r["page_index"] for r in result["page_routes"]] == [0, 1, 2]

    # Nothing dropped at the boundary: all three pages present.
    for marker in (_PAGE1, _PAGE2, _PAGE3):
        assert marker in md, f"{marker} vanished at the seam\n{md}"

    # No content migrates across the seam: each page's section holds only its
    # own marker. Split the concatenated markdown into page sections at the
    # page-2 and page-3 markers (the per-page join is plain \n\n).
    i1 = md.index(_PAGE1)
    i2 = md.index(_PAGE2)
    i3 = md.index(_PAGE3)
    assert i1 < i2 < i3, f"page order broken: {i1}, {i2}, {i3}\n{md}"

    sec1 = md[i1:i2]
    sec2 = md[i2:i3]
    sec3 = md[i3:]

    # Page 1's section: its own markers, NOT page 2's or page 3's.
    assert _PAGE1_WORD in sec1
    assert _PAGE2 not in sec1 and _PAGE3 not in sec1, f"neighbor bled into page1\n{sec1!r}"
    assert _PAGE2_WORD not in sec1 and _PAGE3_WORD not in sec1
    # Page 2's section: only page 2 (no page-1/3 markers or words).
    assert _PAGE2_WORD in sec2
    assert _PAGE1 not in sec2 and _PAGE3 not in sec2, f"neighbor bled into page2\n{sec2!r}"
    assert _PAGE1_WORD not in sec2 and _PAGE3_WORD not in sec2
    # Page 3's section: its own markers, NOT page 1's or page 2's.
    assert _PAGE3_WORD in sec3
    assert _PAGE1 not in sec3 and _PAGE2 not in sec3, f"neighbor bled into page3\n{sec3!r}"
    assert _PAGE1_WORD not in sec3 and _PAGE2_WORD not in sec3

    # Boundary join integrity: adjacent kept pages are joined with EXACTLY \n\n.
    # _join_pages strips each page's rendered markdown and joins with "\n\n". The
    # two chars immediately before page 2's and page 3's section must be that join
    # (a single newline → a dropped join; three+ → an extra-blank-line
    # regression). i2/i3 point at the page markers; back up over the render_markdown
    # heading prefix ("# ") to the true section start, then check the seam.
    for start_idx in (i2, i3):
        seam_start = md.rfind("\n\n", 0, start_idx)
        # Between the \n\n seam and the marker there must be ONLY the heading
        # prefix (no neighbor text leaked into the gap).
        gap = md[seam_start + 2 : start_idx]
        assert seam_start != -1, "missing \\n\\n page join before a section"
        assert gap.strip().rstrip("#").strip() == "", f"unexpected text at seam: {gap!r}"
        # Exactly one blank line at the seam, not a triple newline.
        assert md[seam_start - 1 : seam_start + 2] != "\n\n\n", "more than one blank line at seam"

    # No inline page markers / placeholders leaked into the graded artifact
    # (there is no placeholder under Route B; this also guards against the old
    # Route-A sentinel ever resurfacing).
    assert "PARSER_PAGE_BREAK" not in md


def test_per_page_assembly_seam_two_page_digital_simple(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Same seam-integrity guarantee on the original 2-page digital_simple.pdf.

    Anchors the regression on the pre-existing fixture too (two pages, each
    rendered independently by ``render_markdown`` and joined with ``\\n\\n``):
    page 1 has 'page one' and not 'page two', and vice versa.
    """
    from parser_service import markdown_pipeline
    from parser_service.quality_gate import Decision

    monkeypatch.setattr(
        markdown_pipeline,
        "evaluate_page",
        lambda *a, **k: Decision("keep", None, None),
    )
    monkeypatch.setattr(
        markdown_pipeline,
        "call_vlm",
        lambda *a, **k: {"error": "VLM must not run when every page is kept"},
    )

    result = markdown_pipeline.parse_to_markdown(DIGITAL)
    md = result["markdown"].lower()

    assert "page one" in md and "page two" in md
    i1, i2 = md.index("page one"), md.index("page two")
    assert i1 < i2, md
    sec1, sec2 = md[i1:i2], md[i2:]
    # Boundary integrity: neither page's text crossed into the other's section.
    assert "page two" not in sec1, f"page2 bled into page1 section\n{sec1!r}"
    assert "page one" not in sec2, f"page1 bled into page2 section\n{sec2!r}"
    assert "parser_page_break" not in md
